# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy HTML app to Azure Web App - Jamesapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: echo "No dependencies needed for HTML"
        
      # Optional: Add step to run tests here (if you had any)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: html-app
          path: |
            .
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: html-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4FB1D3898DD2411483E1749F63B93698 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7438005F922B4C5FBE91FC9F129E61A0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_588AC8E1025D45F59F0F38305376A54C }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Jamesapp'
          slot-name: 'Production'
